Update extract_stunnel_arhive.yml

diff --git a/.github/workflows/extract_stunnel_arhive.yml b/.github/workflows/extract_stunnel_arhive.yml
--- a/.github/workflows/extract_stunnel_arhive.yml
+++ b/.github/workflows/extract_stunnel_arhive.yml
@@ -18,16 +18,20 @@ jobs:
       - name: Extract stunnel-5.74.tar.gz
         run: |
           ARCHIVE="stunnel-5.74.tar.gz"
-          ROOT_DIR=$(tar -tf $ARCHIVE | head -1 | cut -f1 -d"/")
-          
-          # Check if the root directory in the archive contains the sources
-          tar -tf $ARCHIVE | grep -q "${ROOT_DIR}/src" && HAS_SRC=true || HAS_SRC=false
 
-          if [ "$HAS_SRC" = "true" ]; then
+          # Check if archive exists
+          if [ ! -f "$ARCHIVE" ]; then
+            echo "Archive $ARCHIVE not found."
+            exit 1
+          fi
+
+          ROOT_DIR=$(tar -tf $ARCHIVE | head -1 | cut -f1 -d"/")
+
+          # Check if the root directory in the archive contains the sources
+          if tar -tf $ARCHIVE | grep -q "${ROOT_DIR}/src"; then
             echo "The archive already contains the source directory, extracting only the contents of ${ROOT_DIR}."
             tar -xzf $ARCHIVE --strip-components=1 -C .
           else
             echo "The archive does not contain the source directory, extracting as is."
             tar -xzf $ARCHIVE -C .
           fi
-          
